name = input("Enter your name: ")
student_id = input("Enter your student ID: ")
department = input("Enter your department: ")
year = input("Enter your year: ")
university = input("Enter your university: ")
phone_number = input("Enter your phone number: ")

print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name: {name}                  |")
print(f"| Student ID: {student_id}                  |")
print(f"| Department: {department}                  |")
print(f"| Year: {year}                  |")
print(f"| University: {university}        |")
print(f"| Phone: {phone_number}       |")
print("+--------------------------------+")